name: Index files

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Create index.mth
      run: |
        python make_index_mth.py
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.4.1
      with:
        commit_message: Create index
